{
 "title": "Node Dashborad",
 "description": "【English version】Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(kube_node_info{node=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds{node=~\"$hostname\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "Nodes Availability",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(kube_node_info) - sum(kube_node_spec_unschedulable)) / sum(kube_node_info) * 100"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(kube_node_info)", "legendFormat": "all_nodes" },
      {
       "expr": "sum (kube_node_status_condition{status=\"true\"})",
       "legendFormat": "node_true"
      },
      {
       "expr": "sum(kube_node_spec_unschedulable)",
       "legendFormat": "node_unschedulable"
      }
     ]
    },
    {
     "title": "Node Availability",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_node_info) - sum(kube_node_spec_unschedulable)) / sum(kube_node_info) * 100"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_node_status_condition{status=\"true\"})by(node)",
       "legendFormat": "node_true_{{node}}"
      },
      {
       "expr": "sum(kube_node_spec_unschedulable)by(node)",
       "legendFormat": "node_unschedulable_{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocatable Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable_pods) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Capacity Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_pods) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Pods Allocation",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(kube_pod_info) by (node)", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Pods Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(kube_pod_info) by (node)", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Pods Availability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_info) by (node) / sum(kube_node_status_allocatable_pods) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "SystemLoad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node=~\"$hostname\",mode='system'}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_capacity_pods{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_1m"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode!=\"idle\"}[1m])))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "System Load Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_15m"
      }
     ]
    },
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 88 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "15m"
      }
     ]
    }
   ]
  },
  { "title": "CPU Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode!=\"idle\"}[30m])))by(node)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU% per core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node=~\"$hostname.*\",mode!=\"idle\"}[1m]))by(cpu)",
     "legendFormat": "Usage_cpu{{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory-Allocation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Used"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_pswpin{node=~\"$hostname.*\"}",
     "legendFormat": "{{node}}-swpin"
    },
    {
     "expr": "node_vmstat_pswpout{node=~\"$hostname.*\"}",
     "legendFormat": "{{node}}-swpout"
    }
   ]
  },
  {
   "title": "Swap Utilization%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "{{node}}-Swap%"
    }
   ]
  },
  {
   "title": "Memory Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 104 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 104 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Allocation: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 128 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Allocation: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Allocation: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Allocation: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 14.399999999999999, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Allocation: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Swap Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 136 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{node=~\"$hostname.*\"})) * 100",
       "legendFormat": "{{node}}-Swap%"
      }
     ]
    },
    {
     "title": "Swap Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 136 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{node=~\"$hostname.*\"})) * 100",
       "legendFormat": "{{node}}-Swap%"
      }
     ]
    },
    {
     "title": "Swap Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 136 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{node=~\"$hostname.*\"})) * 100",
       "legendFormat": "{{node}}-Swap%"
      }
     ]
    },
    {
     "title": "Swap Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 136 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{node=~\"$hostname.*\"})) * 100",
       "legendFormat": "{{node}}-Swap%"
      }
     ]
    },
    {
     "title": "Swap Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{node=~\"$hostname.*\"})) * 100",
       "legendFormat": "{{node}}-Swap%"
      }
     ]
    }
   ]
  },
  { "title": "FileSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "FileSystem_Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"}) by(node)",
     "legendFormat": "used_{{node}}"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"})by(node)",
     "legendFormat": "total_{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 132 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})by(mountpoint)",
       "legendFormat": "used_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 132 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})by(mountpoint)",
       "legendFormat": "used_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 132 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})by(mountpoint)",
       "legendFormat": "used_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})by(mountpoint)",
       "legendFormat": "used_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 143 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})by(mountpoint)",
       "legendFormat": "used_{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space Used% Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used%: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 133 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{node=~\"$hostname.*\"} / node_filesystem_size_bytes{node=~\"$hostname.*\"}) by (node,mountpoint)",
       "legendFormat": "{{node}}_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used%: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 133 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{node=~\"$hostname.*\"} / node_filesystem_size_bytes{node=~\"$hostname.*\"}) by (node,mountpoint)",
       "legendFormat": "{{node}}_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used%: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 133 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{node=~\"$hostname.*\"} / node_filesystem_size_bytes{node=~\"$hostname.*\"}) by (node,mountpoint)",
       "legendFormat": "{{node}}_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used%: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{node=~\"$hostname.*\"} / node_filesystem_size_bytes{node=~\"$hostname.*\"}) by (node,mountpoint)",
       "legendFormat": "{{node}}_{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used%: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 144 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(1 - node_filesystem_avail_bytes{node=~\"$hostname.*\"} / node_filesystem_size_bytes{node=~\"$hostname.*\"}) by (node,mountpoint)",
       "legendFormat": "{{node}}_{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inodes: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 178 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_filesystem_files{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes"
      },
      {
       "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes_free"
      }
     ]
    },
    {
     "title": "Inodes: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_filesystem_files{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes"
      },
      {
       "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes_free"
      }
     ]
    },
    {
     "title": "Inodes: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_filesystem_files{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes"
      },
      {
       "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes_free"
      }
     ]
    },
    {
     "title": "Inodes: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 189 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_filesystem_files{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes"
      },
      {
       "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes_free"
      }
     ]
    },
    {
     "title": "Inodes: $hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 189 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_filesystem_files{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes"
      },
      {
       "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\"})by(node)",
       "legendFormat": "Inodes_free"
      }
     ]
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Disk Utilization%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{node}}_{{device}}"
    }
   ]
  },
  {
   "title": "DiskUtilization% Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 176 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{node=~\"$hostname.*\"}[1m])",
       "legendFormat": "{{node}}_{{device}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 176 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{node=~\"$hostname.*\"}[1m])",
       "legendFormat": "{{node}}_{{device}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 176 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{node=~\"$hostname.*\"}[1m])",
       "legendFormat": "{{node}}_{{device}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 176 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{node=~\"$hostname.*\"}[1m])",
       "legendFormat": "{{node}}_{{device}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 185 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{node=~\"$hostname.*\"}[1m])",
       "legendFormat": "{{node}}_{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk R/W Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_disk_read_time_seconds_total{node=~\"$hostname\"}[1m]))by (node) / avg(irate(node_disk_reads_completed_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}-read"
    },
    {
     "expr": "avg(irate(node_disk_write_time_seconds_total{node=~\"$hostname\"}[1m]))by(node) / avg(irate(node_disk_writes_completed_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}-write"
    }
   ]
  },
  {
   "title": "Disk R/W Bytes",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk IO Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Writes"
    }
   ]
  },
  {
   "title": "Disk avgqu-sz",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_weighted_seconds_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Netrwork", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{node=~\"$hostname\"}",
     "legendFormat": "filefd_{{node}}"
    },
    {
     "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "switches_{{node}}"
    }
   ]
  },
  {
   "title": "File Descriptor Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open  File Descriptor(left)/Context switches(right): $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 226 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$hostname\"}",
       "legendFormat": "filefd_{{node}}"
      },
      {
       "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[1m])",
       "legendFormat": "switches_{{node}}"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right): $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 226 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$hostname\"}",
       "legendFormat": "filefd_{{node}}"
      },
      {
       "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[1m])",
       "legendFormat": "switches_{{node}}"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right): $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 226 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$hostname\"}",
       "legendFormat": "filefd_{{node}}"
      },
      {
       "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[1m])",
       "legendFormat": "switches_{{node}}"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right): $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 226 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$hostname\"}",
       "legendFormat": "filefd_{{node}}"
      },
      {
       "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[1m])",
       "legendFormat": "switches_{{node}}"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right): $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 234 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$hostname\"}",
       "legendFormat": "filefd_{{node}}"
      },
      {
       "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[1m])",
       "legendFormat": "switches_{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])*8",
     "legendFormat": "{{node}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])*8",
     "legendFormat": "{{node}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_drop_total[1m]))by(node)",
     "legendFormat": "{{node}}-receive-drop"
    },
    {
     "expr": "avg(irate(node_network_transmit_drop_total[1m]))by(node)",
     "legendFormat": "{{node}}-transmit-drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_errs_total[1m]))by(node)",
     "legendFormat": "{{node}}-receive-errs"
    },
    {
     "expr": "avg(irate(node_network_transmit_errs_total[1m]))by(node)",
     "legendFormat": "{{node}}-transmit-errs"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Netstat Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Netstat: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 227 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_CurrEstab"
      },
      {
       "expr": "node_netstat_Tcp_ActiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_ActiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InErrs"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network Netstat: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 227 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_CurrEstab"
      },
      {
       "expr": "node_netstat_Tcp_ActiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_ActiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InErrs"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network Netstat: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 227 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_CurrEstab"
      },
      {
       "expr": "node_netstat_Tcp_ActiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_ActiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InErrs"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network Netstat: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 236 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_CurrEstab"
      },
      {
       "expr": "node_netstat_Tcp_ActiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_ActiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InErrs"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network Netstat: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 236 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_CurrEstab"
      },
      {
       "expr": "node_netstat_Tcp_ActiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_ActiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InErrs"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    }
   ]
  },
  {
   "title": "Socket Stat Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network SockStat TCP: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 246 },
     "repeat": "hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_inuse"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_tw"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network SockStat TCP: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 246 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_inuse"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_tw"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network SockStat TCP: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 246 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_inuse"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_tw"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network SockStat TCP: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 255 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_inuse"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_tw"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    },
    {
     "title": "Network SockStat TCP: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 255 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_inuse"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_tw"
      },
      {
       "expr": "node_netstat_Tcp_InSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_InSegs"
      },
      {
       "expr": "node_netstat_Tcp_OutSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_OutSegs"
      },
      {
       "expr": "node_netstat_Tcp_PassiveOpens{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_PassiveOpens"
      },
      {
       "expr": "node_netstat_Tcp_RetransSegs{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_RetransSegs"
      }
     ]
    }
   ]
  }
 ]
}