{
 "title": "Pod Detail Dashborad",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, exported_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace.*\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"}, container)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info: $pod",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_info{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"}"
      }
     ]
    },
    {
     "title": "Pod Availability",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\", phase=\"Running\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\"})",
       "legendFormat": "Pending"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\"})",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Pod Availability Detail",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*.*\", phase=\"Running\"})by(pod)",
       "legendFormat": "Running-{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\"})by(pod)",
       "legendFormat": "Pending-{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\"})by(pod)",
       "legendFormat": "Failed-{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\"})",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Container Availability",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})",
       "legendFormat": "Terminated"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(kube_pod_container_status_running{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Container Availability",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})by(pod,container)",
       "legendFormat": "Ready_{{pod}}_{{container}}"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})by(pod,container)",
       "legendFormat": "Terminated_{{pod}}_{{container}}"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\"})by(pod,container)",
       "legendFormat": "Waiting_{{pod}}_{{container}}"
      },
      {
       "expr": "max(changes(kube_pod_container_status_restarts_total{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\"}[1m]))by(pod)",
       "legendFormat": "Restarts_{{pod}}_{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod / Container Unhealthy Event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Pod Pending / Failed / Unknown",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\"})by(pod)",
     "legendFormat": "Pending-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\"})by(pod)",
     "legendFormat": "Failed-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Container Waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",instance=~\"$node.*\"})by(pod,container)",
     "legendFormat": "Terminated_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",instance=~\"$node.*\"})by(pod,container)",
     "legendFormat": "Terminated_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_restarts_total{exported_namespace=~\"$namespace.*\", pod=~\"$pod.*\",instance=~\"$node.*\"}[1m]))by(pod,container)",
     "legendFormat": "Restarts_{{pod}}_{{container}}"
    }
   ]
  },
  { "title": "Container Unhealthy Reason", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Waiting Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_waiting_reason{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",instance=~\"$node.*\"}[1m])>0)by(pod,reason,container)",
     "legendFormat": "{{pod}}_{{container}} / {{reason}}"
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_terminated_reason{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",instance=~\"$node.*\"}[1m])>0)by(pod,container,reason)",
     "legendFormat": "{{pod}}_{{container}} / {{reason}}"
    }
   ]
  },
  { "title": "Pod CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"$pod.*\", namespace=~\"$namespace.*\",instance=~\"$node.*\",container=\"\",pod!=\"\"}[1m])) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    }
   ]
  },
  {
   "title": "Throttle: $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_cfs_throttled_seconds_total{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",instance=~\"$node.*\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "LoadAverage: $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_load_average_10s{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Process: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_processes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",name!=\"\"})by(pod,name)",
       "legendFormat": "{{pod}}_{{name}}"
      }
     ]
    },
    {
     "title": "File Descriptors: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_file_descriptors{namespace=~\"$namespace.*\",pod=~\"$pod.*\",name!=\"\"})by(pod,name)",
       "legendFormat": "{{pod}}_{{name}}"
      }
     ]
    },
    {
     "title": "CPU: $pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\"}[1m]))",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\"}[1m]))by(name)",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\"}[1m]))by(name)",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Container LoadAverage: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_load_average_10s{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))by(pod)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Container LoadAverage: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_load_average_10s{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))by(pod)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "Pod Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\"}) by (pod)",
     "legendFormat": "Working Set_{{pod}}"
    }
   ]
  },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\"}) by (pod)",
     "legendFormat": "Working Set_{{pod}}"
    },
    {
     "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\"}) by (pod)",
     "legendFormat": "Cache_{{pod}}"
    },
    {
     "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\"}) by (pod)",
     "legendFormat": "RSS_{{pod}}"
    },
    {
     "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\"}) by (pod)",
     "legendFormat": "Mapped File_{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"})",
     "legendFormat": "Requests_{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"})",
     "legendFormat": "Limits_{{pod}}"
    }
   ]
  },
  {
   "title": "Swap Usage: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Failure Count: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (irate(container_memory_failcnt{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[1m])) by (pod)",
     "legendFormat": "failcnt_{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\"})",
       "legendFormat": "MEM"
      },
      {}
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
     "repeat": "container",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\"}) by (container,name)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\"}) by (container,name)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\"})by(device,pod,name)",
       "legendFormat": "usage_{{pod}}_{{device}}_{{name}}"
      }
     ]
    },
    {
     "title": "Inodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_inodes_free{namespace=~\"$namespace.*\",pod=~\"$pod.*\"})by(pod)",
       "legendFormat": "free_{{pod}}"
      },
      {
       "expr": "sum(container_fs_inodes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"})by(pod)",
       "legendFormat": "total_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "repeat": "container",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "repeat": "container",
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "repeat": "container",
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "repeat": "container",
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 89 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "decbytes", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)",
       "legendFormat": "Receive_{{pod}}_bytes"
      },
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)",
       "legendFormat": "Transmit_{{pod}}_bytes"
      }
     ]
    },
    {
     "title": "Network Traffics: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))by(pod)",
       "legendFormat": "Receive_{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))by(pod)",
       "legendFormat": "Transmit_{{pod}}"
      }
     ]
    },
    {
     "title": "Network-Dropped: $pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))",
       "legendFormat": "Receive-Dropped"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))",
       "legendFormat": "Transmit-Dropped"
      }
     ]
    },
    {
     "title": "Network-Errors: $pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))",
       "legendFormat": "Receive-Errors"
      },
      {
       "expr": "sum(irate(container_network_transmit_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\"}[1m]))",
       "legendFormat": "Transmit-Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "repeat": "container",
     "yaxes": [
      { "format": "decbytes", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\"}[5m])) by (pod)",
       "legendFormat": "Receive_{{pod}}_bytes"
      },
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\"}[5m])) by (pod)",
       "legendFormat": "Transmit_{{pod}}_bytes"
      }
     ]
    },
    {
     "title": "Network Traffic Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "decbytes", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\"}[5m])) by (pod)",
       "legendFormat": "Receive_{{pod}}_bytes"
      },
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\"}[5m])) by (pod)",
       "legendFormat": "Transmit_{{pod}}_bytes"
      }
     ]
    },
    {
     "title": "Network Traffics: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "repeat": "container",
     "yaxes": [
      { "format": "short", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))by(pod)",
       "legendFormat": "Receive_{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))by(pod)",
       "legendFormat": "Transmit_{{pod}}"
      }
     ]
    },
    {
     "title": "Network Traffics: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "Receive (-) / transmit (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))by(pod)",
       "legendFormat": "Receive_{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))by(pod)",
       "legendFormat": "Transmit_{{pod}}"
      }
     ]
    },
    {
     "title": "Network-Dropped: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Receive-Dropped"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Transmit-Dropped"
      }
     ]
    },
    {
     "title": "Network-Dropped: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Receive-Dropped"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Transmit-Dropped"
      }
     ]
    },
    {
     "title": "Network-Errors: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Receive-Errors"
      },
      {
       "expr": "sum(irate(container_network_transmit_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Transmit-Errors"
      }
     ]
    },
    {
     "title": "Network-Errors: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Receive-Errors"
      },
      {
       "expr": "sum(irate(container_network_transmit_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\"}[1m]))",
       "legendFormat": "Transmit-Errors"
      }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } }
 ]
}